general:
  verbose: true
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: '67623890-adb5-4285-b8ff-753b2785e5bf'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
